---
title: "Bertsimas and Mazumder"
output: html_document
editor_options: 
  chunk_output_type: console
---



Bertsimas and Mazumder (2014)

```{r}
gen_sample <- function(m,n,my_pi,type, i) {
  X <- matrix(rnorm(m*n, sd=100),
              ncol=n)
  eps <- rnorm(m, sd=10)
  beta <- rep(1, n)
  y <- X %*% beta + eps
  outliers <- sample(1:m, size=floor(my_pi*m))
  if (type == "A") {
    X[outliers,1] <- X[outliers,1] + 1000
  } else if (type == "B") {
    x_outliers <- outliers[1:floor(length(outliers)/2)]
    y_outliers <- outliers[(floor(length(outliers)/2)+1):length(outliers)]
    X[x_outliers,1] <- X[x_outliers,1] + 1000
    y[y_outliers] <- y[y_outliers] + 1000
  }
  X <- rbind(X[-outliers,], X[outliers,])
  y <- c(y[-outliers], y[outliers])
  my_data <- data.frame(y, X)
  write.table(my_data, file=paste("bm_small/m",
                                m-length(outliers),
                                "n",n+1, 
                                "m_outliers", length(outliers), 
                                "i", i, 
                                ".csv",
                                sep=""),
            quote=FALSE,
            row.names=FALSE,
            col.names=FALSE,
            sep=","
  )
}
```



```{r}
set.seed(12345)
for (i in 0:99) {
    m <- sample(25:60,1)
    n <- sample(3:10,1)
    gen_sample(m, n, 0.4, "B", i) # Ex-1
    
}
```


